name: book_store
description: A new Flutter project.
publish_to:

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  google_fonts: ^6.2.1
  dio: ^5.8.0+1
  http: 1.3.0
  shared_preferences: ^2.0.15
  rive_splash_screen: ^0.1.1
  flutter_svg: ^2.1.0
  rate_in_stars: ^0.0.3
  water_drop_nav_bar: ^2.2.0+4
  cupertino_icons: ^1.0.2
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.0.0+2
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/